permalink:           none

# Setup
title:               Lucas Mazza
tagline:             'Writes code, rants constantly, blogs about it eventually.'
description:         'Developer @ <a href="http://plataformatec.com.br">Plataformatec</a>.'
url:                 http://lucasmazza.github.io
baseurl:             ''

# About/contact
author:
  name:              Lucas Mazza
  url:               https://twitter.com/lucasmazza
  email:             lucastmazza@gmail.com

# Custom vars
version:             1.0.0

exclude:
  - script
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - bin

collections:
  talks:
    output: true
    permalink: /talks/:title.html

highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

# Jekyll SEO Tag settings

twitter:
  username: lucasmazza
