baseURL: https://lucasmazza.website/
title: Lucas Mazza

disablePathToLower: true
removePathAccents: true
languageCode: en-us

permalinks:
  talks: '/talks/:slug'

markup:
  highlight:
    style: tango

menu:
  main:
    - name: 'Livro HTML5 e CSS 3 →'
      url: 'https://lucasmazza.website/htmlcss-exemplos'
      identifier: livro
      weight: 400

    - name: 'Receitas →'
      url: 'https://lucasmazza.notion.site/lucasmazza/Receitas-79a5a48a2350465dad3c57ba866f95d4'
      identifier: receitas
      weight: 500

security:
  exec:
    osEnv:
      - '(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$'
      - ^ASDF_DIR$
      - ^HOME$