#!/usr/bin/env ruby

unless ARGV[0]
  puts 'Usage: script/generate "Post Title"'
  exit(-1)
end

date_prefix = Time.now.strftime('%Y-%m-%d')
post_name = ARGV.join ' '
permalink = post_name.strip.downcase.gsub(/[^a-zA-Z0-9]/, '-')
filename = "#{date_prefix}-#{permalink}.md"
post = File.expand_path("../_drafts/#{filename}", File.dirname(__FILE__))

header = <<-END
---
layout: post
title: #{post_name}
description: Description goes here...
---

Body text goes here...
END

File.open(post, 'w') do |f|
  f << header
end

editor = ENV['EDITOR']
system(editor, post) if editor
exit(0)
